version: "3.2"
services:
    static-web:
        build: ../Step_1

    dynamic-web:
        build: ../Step_2

    reverse-proxy:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - "./nginx-reverse-dc.conf:/etc/nginx/conf.d/default.conf"
