version: "3.2"
services:
    reverse:
        image: nginx:latest
        volumes: 
            - "./nginx-reverse.conf:/etc/nginx/conf.d/default.conf"
        ports:
            - "80:80"

    static:
        build: ../Step_1

    dynamic:
        build: ../Step_2
